// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZbwJHaYlfrfFQ76W-5m9bsAm2TTL9CHY',
    appId: '1:280338531842:web:215087d5ac9fec34b2c91b',
    messagingSenderId: '280338531842',
    projectId: 'efficient-d35fb',
    authDomain: 'efficient-d35fb.firebaseapp.com',
    storageBucket: 'efficient-d35fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL89axhTeNNCb2uSBDFz18osWc4nWTHN0',
    appId: '1:280338531842:android:1b71fbe186618752b2c91b',
    messagingSenderId: '280338531842',
    projectId: 'efficient-d35fb',
    storageBucket: 'efficient-d35fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADP0VsK6CfYY9yrfKx7QGoSti0Q3B92E',
    appId: '1:280338531842:ios:33abab1eaa0880a5b2c91b',
    messagingSenderId: '280338531842',
    projectId: 'efficient-d35fb',
    storageBucket: 'efficient-d35fb.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAADP0VsK6CfYY9yrfKx7QGoSti0Q3B92E',
    appId: '1:280338531842:ios:33abab1eaa0880a5b2c91b',
    messagingSenderId: '280338531842',
    projectId: 'efficient-d35fb',
    storageBucket: 'efficient-d35fb.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZbwJHaYlfrfFQ76W-5m9bsAm2TTL9CHY',
    appId: '1:280338531842:web:8e529a407eb8dd67b2c91b',
    messagingSenderId: '280338531842',
    projectId: 'efficient-d35fb',
    authDomain: 'efficient-d35fb.firebaseapp.com',
    storageBucket: 'efficient-d35fb.appspot.com',
  );
}
